from . import graph_config
from . import whatsapp_account
from . import whatsapp_api
from . import whatsapp_contact_profile
from . import whatsapp_group
from . import whatsapp_message
from . import whatsapp_template
from . import crm_lead
from . import res_partner
from . import res_config_settings
