{
    'name': 'CRM Marketing Full Suite',
    'version': '18.0.1.0.0',
    'category': 'CRM',
    'summary': 'CRM, Marketing, Communication, LinkedIn, Meta, WhatsApp, Email, AI, Robinson, RGPD',
    'description': """
CRM Marketing Full Suite is a premium unified module blending CRM communication logging, multi-user Gmail synchronization, B2B marketing campaigns, AI custom copywriting, and LinkedIn Growth routines.
Developed by Vantis.
Official Website: https://vantis.uniasser.net
Support Email: info@uniasser.com
""",
    'author': 'Vantis',
    'website': 'https://vantis.uniasser.net',
    'depends': ['crm', 'uniasser_whatsapp'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'security/linkedin_security.xml',
        'data/ir_cron.xml',
        'data/ir_cron_drip.xml',
        'data/ir_cron_linkedin.xml',
        'data/marketing_channel_data.xml',
        'data/linkedin_data.xml',
        'data/linkedin_seed_data.xml',
        'data/linkedin_seed_data_new.xml',
        'views/crm_email_template_views.xml',
        'views/crm_communication_views.xml',
        'views/crm_lead_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_users_views.xml',
        'views/marketing_esp_provider_views.xml',
        'views/marketing_channel_views.xml',
        'views/marketing_pain_point_views.xml',
        'views/marketing_rgpd_views.xml',
        'views/marketing_robinson_views.xml',
        'views/marketing_ai_template_views.xml',
        'views/marketing_campaign_lead_views.xml',
        'views/marketing_campaign_views.xml',
        'views/linkedin_profile_views.xml',
        'views/linkedin_post_views.xml',
        'views/linkedin_signal_views.xml',
        'views/linkedin_batch_views.xml',
        'views/linkedin_diagnostic_views.xml',
        'views/linkedin_capture_views.xml',
        'views/linkedin_prosp_views.xml',
        'views/crm_lead_linkedin_views.xml',
        'views/menus.xml',
        'views/linkedin_menus.xml',
        'wizard/enrich_batch_views.xml',
        'wizard/campaign_create_wizard_views.xml',
        'wizard/followup_launch_wizard_views.xml',
        'wizard/linkedin_import_wizard_views.xml',
        'wizard/add_to_campaign_views.xml',
        'wizard/import_template_views.xml',
        'wizard/linkedin_convert_opportunity_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'crm_marketing_and_comunications/static/src/css/crm_communication.css',
            'crm_marketing_and_comunications/static/src/css/marketing_campaigns.css',
            'crm_marketing_and_comunications/static/src/js/hex_color_field.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': 169.00,
    'currency': 'EUR',
}
