{
    'name': 'Uniasser WhatsApp',
    'version': '18.0.1.0.0',
    'summary': 'Integración WhatsApp Business Cloud API (Meta) — Odoo 18 CE',
    'author': 'Uniasser',
    'license': 'LGPL-3',
    'category': 'Discuss',
    'depends': ['base', 'mail', 'crm', 'contacts'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/mail_message_subtype.xml',
        'data/ir_cron.xml',
        'views/whatsapp_account_views.xml',
        'views/whatsapp_template_views.xml',
        'views/whatsapp_message_views.xml',
        'views/whatsapp_send_wizard_views.xml',
        'views/crm_lead_views.xml',
        'views/res_partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'uniasser_whatsapp/static/src/css/whatsapp_chat.css',
            'uniasser_whatsapp/static/src/xml/whatsapp_chat.xml',
            'uniasser_whatsapp/static/src/components/WhatsAppChat.js',
            'uniasser_whatsapp/static/src/components/WhatsAppConversationList.js',
            'uniasser_whatsapp/static/src/components/WhatsAppMessageThread.js',
            'uniasser_whatsapp/static/src/components/WhatsAppComposer.js',
            'uniasser_whatsapp/static/src/components/WhatsAppNewMessage.js',
        ],
    },
    'installable': True,
    'application': True,
    'sequence': 100,
}
